on:
  repository_dispatch:
    types: [deployment_success]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
